from __future__ import annotations

from lab4.isa import Opcode

COMMON_CYCLE = ("FETCH_HEADER",)

MICROPROGRAMS: dict[Opcode, tuple[str, ...]] = {
    Opcode.NOP: ("COMMIT",),
    Opcode.HALT: ("COMMIT",),
    Opcode.MOV: ("READ_SOURCE", "WRITE_DESTINATION", "COMMIT"),
    Opcode.ADD: ("READ_LEFT", "READ_RIGHT", "ALU_ADD", "WRITE_BACK", "UPDATE_FLAGS", "COMMIT"),
    Opcode.SUB: ("READ_LEFT", "READ_RIGHT", "ALU_SUB", "WRITE_BACK", "UPDATE_FLAGS", "COMMIT"),
    Opcode.MUL: ("READ_LEFT", "READ_RIGHT", "ALU_MUL", "WRITE_BACK", "UPDATE_FLAGS", "COMMIT"),
    Opcode.DIV: ("READ_LEFT", "READ_RIGHT", "ALU_DIV", "WRITE_BACK", "UPDATE_FLAGS", "COMMIT"),
    Opcode.MOD: ("READ_LEFT", "READ_RIGHT", "ALU_MOD", "WRITE_BACK", "UPDATE_FLAGS", "COMMIT"),
    Opcode.CMP: ("READ_LEFT", "READ_RIGHT", "ALU_SUB", "UPDATE_FLAGS", "COMMIT"),
    Opcode.JMP: ("READ_TARGET", "EVALUATE_BRANCH", "COMMIT"),
    Opcode.JZ: ("READ_TARGET", "EVALUATE_BRANCH", "COMMIT"),
    Opcode.JNZ: ("READ_TARGET", "EVALUATE_BRANCH", "COMMIT"),
    Opcode.JG: ("READ_TARGET", "EVALUATE_BRANCH", "COMMIT"),
    Opcode.JGE: ("READ_TARGET", "EVALUATE_BRANCH", "COMMIT"),
    Opcode.JL: ("READ_TARGET", "EVALUATE_BRANCH", "COMMIT"),
    Opcode.JLE: ("READ_TARGET", "EVALUATE_BRANCH", "COMMIT"),
    Opcode.PUSH: ("READ_SOURCE", "STACK_DEC", "MEM_WRITE_STACK", "COMMIT"),
    Opcode.POP: ("MEM_READ_STACK", "WRITE_DESTINATION", "STACK_INC", "COMMIT"),
    Opcode.CALL: ("READ_TARGET", "STACK_DEC", "MEM_WRITE_RETURN", "SET_PC", "COMMIT"),
    Opcode.RET: ("MEM_READ_STACK", "STACK_INC", "SET_PC", "COMMIT"),
    Opcode.LOADB: ("READ_BYTE_SOURCE", "WRITE_DESTINATION", "COMMIT"),
    Opcode.STOREB: ("READ_BYTE_VALUE", "WRITE_BYTE_DESTINATION", "COMMIT"),
    Opcode.POLY: ("READ_X", "READ_COEFFICIENTS", "CISC_POLY_EVALUATE", "WRITE_DESTINATION", "UPDATE_FLAGS", "COMMIT"),
    Opcode.SSON: ("SET_SUPERSCALAR_ON", "COMMIT"),
    Opcode.SSOFF: ("SET_SUPERSCALAR_OFF", "COMMIT"),
}
